name: Build and Deploy Hugo

on:
  push:
    branches:
      - main

jobs:
  hugo-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive   # fetch your theme submodule
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'
          extended: true

      - name: Build Hugo site
        run: hugo --config hugo.yaml  

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
